services:
  web:
    build: .
    ports:
      - "81:80"
    volumes:
      - ./site:/var/www/html
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 300M
    networks:
      - webnet

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jogos_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
